apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fwdr.fullname" . }}
  labels:
    {{- include "fwdr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fwdr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fwdr.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: fwdr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.forwarders }}
            - containerPort: {{ .destinationPort }}
            {{- end }}
          volumeMounts:
            - name: settings
              mountPath: /app/settings.yaml
              subPath: settings.yaml
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: settings
          configMap:
            name: {{ include "fwdr.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
